# Generated by Django 4.2.1 on 2023-05-10 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=223, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_birth',
            field=models.CharField(blank=True, max_length=132, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='given_name',
            field=models.CharField(blank=True, max_length=132, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=132, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_expire',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=40)),
                ('family_status', models.CharField(max_length=333)),
                ('count_child', models.CharField(max_length=50)),
                ('social_status', models.CharField(max_length=333)),
                ('main_problem', models.CharField(max_length=333)),
                ('mental_problem', models.CharField(max_length=333)),
                ('relative_problem', models.CharField(max_length=333)),
                ('husband_problem', models.CharField(max_length=333)),
                ('divorce_problem', models.CharField(max_length=333)),
                ('not_married_problem', models.CharField(max_length=333)),
                ('sexual_problem', models.CharField(max_length=333)),
                ('child_problem', models.CharField(max_length=333)),
                ('work_problem', models.CharField(max_length=333)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.region')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.district'),
        ),
    ]
