# Generated by Django 4.2.1 on 2023-05-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_region_remove_user_email_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='name_ky',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='name_uz',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_ky',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_uz',
            field=models.CharField(max_length=123, null=True),
        ),
    ]
