# Generated by Django 4.2.1 on 2023-05-08 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterTestVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RegisterVariantsVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_variant', to='main.registertestvariant')),
            ],
        ),
        migrations.RenameField(
            model_name='registertest',
            old_name='question',
            new_name='question_name',
        ),
        migrations.CreateModel(
            name='ThirdVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_variant', to='main.registervariantsvariant')),
            ],
        ),
        migrations.AddField(
            model_name='registertestvariant',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_variant', to='main.registertest'),
        ),
    ]
