# Generated by Django 4.2.1 on 2023-05-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_registertestvariant_registervariantsvariant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintest',
            name='answer_a_ky',
            field=models.CharField(max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='maintest',
            name='answer_a_uz',
            field=models.CharField(max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='maintest',
            name='answer_b_ky',
            field=models.CharField(max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='maintest',
            name='answer_b_uz',
            field=models.CharField(max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='maintest',
            name='answer_c_ky',
            field=models.CharField(blank=True, max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='maintest',
            name='answer_c_uz',
            field=models.CharField(blank=True, max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='maintest',
            name='answer_d_ky',
            field=models.CharField(blank=True, max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='maintest',
            name='answer_d_uz',
            field=models.CharField(blank=True, max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='maintest',
            name='question_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='maintest',
            name='question_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='maintest',
            name='true_answer_ky',
            field=models.CharField(max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='maintest',
            name='true_answer_uz',
            field=models.CharField(max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='comment_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='comment_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='red_title_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='red_title_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='some_title_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='some_title_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_desc_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_desc_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionvariant',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionvariant',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registertest',
            name='question_name_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registertest',
            name='question_name_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registertestvariant',
            name='name_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registertestvariant',
            name='name_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registervariantsvariant',
            name='name_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registervariantsvariant',
            name='name_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='thirdvariant',
            name='name_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='thirdvariant',
            name='name_uz',
            field=models.TextField(null=True),
        ),
    ]
