# Generated by Django 4.2.1 on 2023-05-10 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_maintest_answer_a_ky_maintest_answer_a_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registervariantsvariant',
            name='var',
        ),
        migrations.RemoveField(
            model_name='thirdvariant',
            name='var',
        ),
        migrations.RemoveField(
            model_name='registertest',
            name='question_name_ky',
        ),
        migrations.RemoveField(
            model_name='registertest',
            name='question_name_uz',
        ),
        migrations.AddField(
            model_name='registertest',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registertest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RegisterTestVariant',
        ),
        migrations.DeleteModel(
            name='RegisterVariantsVariant',
        ),
        migrations.DeleteModel(
            name='ThirdVariant',
        ),
    ]
