# Generated by Django 4.2.1 on 2023-05-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_registervariantsvariant_var_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintest',
            name='true_answer_ky',
        ),
        migrations.RemoveField(
            model_name='maintest',
            name='true_answer_uz',
        ),
        migrations.AddField(
            model_name='maintest',
            name='answer_e',
            field=models.CharField(blank=True, max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='maintest',
            name='answer_e_ky',
            field=models.CharField(blank=True, max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='maintest',
            name='answer_e_uz',
            field=models.CharField(blank=True, max_length=221, null=True),
        ),
    ]
