# Generated by Django 4.2.1 on 2023-05-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='text_uz',
            field=models.TextField(null=True),
        ),
    ]
