# Generated by Django 4.2.1 on 2023-05-11 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_workout_text_ky_workout_text_uz'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionVariantForFirst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_uz', models.TextField(null=True)),
                ('text_ky', models.TextField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_first_question', to='main.question')),
            ],
        ),
    ]
